version: '3.8'
services:
  gamesapi:
    container_name: gamesapi
    depends_on:
      - "dbapi"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION_STRING: "host=dbapi;port=5432;database=games;username=postgres;password=124356"
    ports:
      - "5000:80"
    
  dbapi:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 124356
      POSTGRES_DB: games
    ports:
      - "5432:5432"
   

  
    